/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b4c1ff",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#e48fec",
        "on-surface": "#ffffff",
        "on-error": "#490006",
        "inverse-on-surface": "#565554",
        "secondary-container": "#1f3da1",
        "on-primary-fixed": "#000000",
        "inverse-surface": "#fcf8f8",
        "surface-container-highest": "#262626",
        "surface-container-high": "#201f1f",
        "on-error-container": "#ffa8a3",
        "on-background": "#ffffff",
        "outline-variant": "#484847",
        "secondary": "#7f98ff",
        "surface-dim": "#0e0e0e",
        "on-secondary-container": "#c5ceff",
        "on-primary-fixed-variant": "#002a61",
        "surface-tint": "#85adff",
        "primary-container": "#6c9fff",
        "error-dim": "#d7383b",
        "on-tertiary-container": "#60136d",
        "inverse-primary": "#005bc2",
        "error": "#ff716c",
        "on-secondary-fixed-variant": "#2c48ac",
        "tertiary-fixed-dim": "#e48fec",
        "tertiary-container": "#f39cfb",
        "secondary-dim": "#7f98ff",
        "error-container": "#9f0519",
        "on-tertiary": "#6b1f77",
        "on-primary-container": "#00214f",
        "surface": "#0e0e0e",
        "tertiary": "#fab0ff",
        "primary-fixed-dim": "#5191ff",
        "primary": "#85adff",
        "on-tertiary-fixed": "#41004d",
        "outline": "#777575",
        "surface-container": "#1a1919",
        "on-secondary-fixed": "#00288d",
        "on-secondary": "#00185e",
        "on-primary": "#002c65",
        "on-tertiary-fixed-variant": "#6a1f76",
        "background": "#0e0e0e",
        "tertiary-fixed": "#f39cfb",
        "surface-container-low": "#131313",
        "on-surface-variant": "#adaaaa",
        "primary-dim": "#0070eb",
        "primary-fixed": "#6c9fff",
        "surface-variant": "#262626",
        "surface-bright": "#2c2c2c",
        "secondary-fixed": "#c6cfff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
